"""
Constants that hold all the clusters
"""
GRAHAM = 'GRAHAM'
CEDAR = 'CEDAR'
GUILLIMIN = 'GUILLIMIN'

AVAILABLE_CLUSTERS = (GRAHAM, CEDAR, GUILLIMIN)
SLURM_CLUSTERS = (CEDAR, GRAHAM)
MOAB_CLUSTERS = (GUILLIMIN, )